// Auth actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Review Cards
export const MARK_REVIEWED = 'MARK_REVIEWED';
export const MARK_AGAIN = 'MARK_AGAIN';
export const FETCH_REVIEW_CARDS_START = 'FETCH_REVIEW_CARDS_START';
export const FETCH_REVIEW_CARDS_SUCCESS = 'FETCH_REVIEW_CARDS_SUCCESS';
export const FETCH_REVIEW_CARDS_FAIL = 'FETCH_REVIEW_CARDS_FAIL';